[workspace]
members = [
    "connection-pool",
    "migrations/*"
]


[workspace.dependencies]
anyhow = "1.0.75"
diesel = { version = "2.1.3", features = ["r2d2", "postgres"] }
dotenv = "0.15.0"
sqlx = { version = "0.7", features = [ "runtime-tokio", "postgres", "uuid", "time", "chrono", "json" ] }
tokio = { version = "1.34.0", features = ["full"] }
