[workspace]
members = [
    "connection-pool",
    "migrations/*",
    "query-and-indexing/*"
]


[workspace.dependencies]
anyhow = "1.0.75"
diesel = { version = "2.1.3", features = ["r2d2", "postgres", "serde_json"] }
diesel_migrations = "2.1.0"
dotenv = "0.15.0"
sqlx = { version = "0.7", features = [ "runtime-tokio", "postgres", "uuid", "time", "chrono", "json" ] }
tokio = { version = "1.34.0", features = ["full"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.93"}
itertools = "0.12.0"
clap = { version = "4.3.8", features = ["derive", "std"], default-features = false }
