version: '3.8'
services:
  connection_pool:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=connection_pool
    ports:
      - '5432:5432'
